name: cookbook_final
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  provider: ^6.1.5
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/foodImg.jpeg
    - assets/images/Logo.png
    - assets/images/app_Logo.png

  fonts:
    - family: ArialRounded
      fonts:
        - asset: assets/fonts/ARIALROUNDEDMT.TTF
        - asset: assets/fonts/ARLRDBD.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_Logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_Logo.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/app_Logo.png"
    background_color: "#FFFFFF"
  macos:
    generate: true
    image_path: "assets/images/app_Logo.png"
